# Server
server.port=8080

# Database - Aiven MySQL
spring.datasource.url=jdbc:mysql://mysql-224c4940-anurag-9dba.l.aivencloud.com:16389/defaultdb?sslMode=REQUIRED&useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&trustServerCertificate=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ODGRO_DFciPnoSW0H58
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Initialize seed data
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true

# JWT
app.jwt.secret=${JWT_SECRET:GardenAdvisorSecretKey2024SuperSecureKeyForJWT}
app.jwt.expiration=86400000

# CORS

app.cors.allowed-origins=http://localhost:3000,https://kharipriyaa26.vercel.app

# Logging
logging.level.com.gardenadvisor=DEBUG
logging.level.org.springframework.security=INFO